// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOd3-kCUsnYL7ky8ruEgvr9Ec-KJp-4Ss',
    appId: '1:893131752313:web:9c6b6a1a571451cb82a5a8',
    messagingSenderId: '893131752313',
    projectId: 'flutter-eas-mobile-apps',
    authDomain: 'flutter-eas-mobile-apps.firebaseapp.com',
    storageBucket: 'flutter-eas-mobile-apps.firebasestorage.app',
    measurementId: 'G-5VTCLBRTK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv228FNqNHBBbp4GIajELs08Chi1vgEbE',
    appId: '1:893131752313:android:e849130a36065c3082a5a8',
    messagingSenderId: '893131752313',
    projectId: 'flutter-eas-mobile-apps',
    storageBucket: 'flutter-eas-mobile-apps.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGEmK47zOhOWizHdVp-WhRiXbkWZlYwk',
    appId: '1:893131752313:ios:e4b11f187387a2e182a5a8',
    messagingSenderId: '893131752313',
    projectId: 'flutter-eas-mobile-apps',
    storageBucket: 'flutter-eas-mobile-apps.firebasestorage.app',
    iosBundleId: 'com.example.easAppsMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGEmK47zOhOWizHdVp-WhRiXbkWZlYwk',
    appId: '1:893131752313:ios:e4b11f187387a2e182a5a8',
    messagingSenderId: '893131752313',
    projectId: 'flutter-eas-mobile-apps',
    storageBucket: 'flutter-eas-mobile-apps.firebasestorage.app',
    iosBundleId: 'com.example.easAppsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOd3-kCUsnYL7ky8ruEgvr9Ec-KJp-4Ss',
    appId: '1:893131752313:web:0f7aae6569dc37ec82a5a8',
    messagingSenderId: '893131752313',
    projectId: 'flutter-eas-mobile-apps',
    authDomain: 'flutter-eas-mobile-apps.firebaseapp.com',
    storageBucket: 'flutter-eas-mobile-apps.firebasestorage.app',
    measurementId: 'G-WSTP9X56WX',
  );
}
